//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FinalExam.Computation {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AccountancyComputationsBinding", Namespace="urn:businesscomp")]
    public partial class AccountancyComputations : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback calculateInterestOperationCompleted;
        
        private System.Threading.SendOrPostCallback calculateInterestRateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SimpleInterestOperationCompleted;
        
        private System.Threading.SendOrPostCallback CompoundInterestOperationCompleted;
        
        private System.Threading.SendOrPostCallback calculateDiscountOperationCompleted;
        
        private System.Threading.SendOrPostCallback straightLineDepreciationOperationCompleted;
        
        private System.Threading.SendOrPostCallback unitofProductOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AccountancyComputations() {
            this.Url = "http://172.18.17.72:8080/it140p/service.php";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event calculateInterestCompletedEventHandler calculateInterestCompleted;
        
        /// <remarks/>
        public event calculateInterestRateCompletedEventHandler calculateInterestRateCompleted;
        
        /// <remarks/>
        public event SimpleInterestCompletedEventHandler SimpleInterestCompleted;
        
        /// <remarks/>
        public event CompoundInterestCompletedEventHandler CompoundInterestCompleted;
        
        /// <remarks/>
        public event calculateDiscountCompletedEventHandler calculateDiscountCompleted;
        
        /// <remarks/>
        public event straightLineDepreciationCompletedEventHandler straightLineDepreciationCompleted;
        
        /// <remarks/>
        public event unitofProductCompletedEventHandler unitofProductCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://172.18.17.72/it140p/service.php/calculateInterest", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string calculateInterest(float principal, float interestRate, float time) {
            object[] results = this.Invoke("calculateInterest", new object[] {
                        principal,
                        interestRate,
                        time});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void calculateInterestAsync(float principal, float interestRate, float time) {
            this.calculateInterestAsync(principal, interestRate, time, null);
        }
        
        /// <remarks/>
        public void calculateInterestAsync(float principal, float interestRate, float time, object userState) {
            if ((this.calculateInterestOperationCompleted == null)) {
                this.calculateInterestOperationCompleted = new System.Threading.SendOrPostCallback(this.OncalculateInterestOperationCompleted);
            }
            this.InvokeAsync("calculateInterest", new object[] {
                        principal,
                        interestRate,
                        time}, this.calculateInterestOperationCompleted, userState);
        }
        
        private void OncalculateInterestOperationCompleted(object arg) {
            if ((this.calculateInterestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calculateInterestCompleted(this, new calculateInterestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://172.18.17.72/it140p/service.php/calculateInterestRate", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public float calculateInterestRate(float simplePrincipal, float principal, float time) {
            object[] results = this.Invoke("calculateInterestRate", new object[] {
                        simplePrincipal,
                        principal,
                        time});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void calculateInterestRateAsync(float simplePrincipal, float principal, float time) {
            this.calculateInterestRateAsync(simplePrincipal, principal, time, null);
        }
        
        /// <remarks/>
        public void calculateInterestRateAsync(float simplePrincipal, float principal, float time, object userState) {
            if ((this.calculateInterestRateOperationCompleted == null)) {
                this.calculateInterestRateOperationCompleted = new System.Threading.SendOrPostCallback(this.OncalculateInterestRateOperationCompleted);
            }
            this.InvokeAsync("calculateInterestRate", new object[] {
                        simplePrincipal,
                        principal,
                        time}, this.calculateInterestRateOperationCompleted, userState);
        }
        
        private void OncalculateInterestRateOperationCompleted(object arg) {
            if ((this.calculateInterestRateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calculateInterestRateCompleted(this, new calculateInterestRateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://172.18.17.72/it140p/service.php/SimpleInterest", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public float SimpleInterest(float principal, float rate, float time) {
            object[] results = this.Invoke("SimpleInterest", new object[] {
                        principal,
                        rate,
                        time});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void SimpleInterestAsync(float principal, float rate, float time) {
            this.SimpleInterestAsync(principal, rate, time, null);
        }
        
        /// <remarks/>
        public void SimpleInterestAsync(float principal, float rate, float time, object userState) {
            if ((this.SimpleInterestOperationCompleted == null)) {
                this.SimpleInterestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSimpleInterestOperationCompleted);
            }
            this.InvokeAsync("SimpleInterest", new object[] {
                        principal,
                        rate,
                        time}, this.SimpleInterestOperationCompleted, userState);
        }
        
        private void OnSimpleInterestOperationCompleted(object arg) {
            if ((this.SimpleInterestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SimpleInterestCompleted(this, new SimpleInterestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://172.18.17.72/it140p/service.php/CompoundInterest", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public float CompoundInterest(float prin, float rate, float time, float n) {
            object[] results = this.Invoke("CompoundInterest", new object[] {
                        prin,
                        rate,
                        time,
                        n});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void CompoundInterestAsync(float prin, float rate, float time, float n) {
            this.CompoundInterestAsync(prin, rate, time, n, null);
        }
        
        /// <remarks/>
        public void CompoundInterestAsync(float prin, float rate, float time, float n, object userState) {
            if ((this.CompoundInterestOperationCompleted == null)) {
                this.CompoundInterestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompoundInterestOperationCompleted);
            }
            this.InvokeAsync("CompoundInterest", new object[] {
                        prin,
                        rate,
                        time,
                        n}, this.CompoundInterestOperationCompleted, userState);
        }
        
        private void OnCompoundInterestOperationCompleted(object arg) {
            if ((this.CompoundInterestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompoundInterestCompleted(this, new CompoundInterestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://172.18.17.72/it140p/service.php/calculateDiscount", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public float calculateDiscount(float listPrice, float sellingPrice) {
            object[] results = this.Invoke("calculateDiscount", new object[] {
                        listPrice,
                        sellingPrice});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void calculateDiscountAsync(float listPrice, float sellingPrice) {
            this.calculateDiscountAsync(listPrice, sellingPrice, null);
        }
        
        /// <remarks/>
        public void calculateDiscountAsync(float listPrice, float sellingPrice, object userState) {
            if ((this.calculateDiscountOperationCompleted == null)) {
                this.calculateDiscountOperationCompleted = new System.Threading.SendOrPostCallback(this.OncalculateDiscountOperationCompleted);
            }
            this.InvokeAsync("calculateDiscount", new object[] {
                        listPrice,
                        sellingPrice}, this.calculateDiscountOperationCompleted, userState);
        }
        
        private void OncalculateDiscountOperationCompleted(object arg) {
            if ((this.calculateDiscountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calculateDiscountCompleted(this, new calculateDiscountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://172.18.17.72/it140p/service.php/straightLineDepreciation", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public float straightLineDepreciation(float cost, float residual, float assetlife) {
            object[] results = this.Invoke("straightLineDepreciation", new object[] {
                        cost,
                        residual,
                        assetlife});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void straightLineDepreciationAsync(float cost, float residual, float assetlife) {
            this.straightLineDepreciationAsync(cost, residual, assetlife, null);
        }
        
        /// <remarks/>
        public void straightLineDepreciationAsync(float cost, float residual, float assetlife, object userState) {
            if ((this.straightLineDepreciationOperationCompleted == null)) {
                this.straightLineDepreciationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnstraightLineDepreciationOperationCompleted);
            }
            this.InvokeAsync("straightLineDepreciation", new object[] {
                        cost,
                        residual,
                        assetlife}, this.straightLineDepreciationOperationCompleted, userState);
        }
        
        private void OnstraightLineDepreciationOperationCompleted(object arg) {
            if ((this.straightLineDepreciationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.straightLineDepreciationCompleted(this, new straightLineDepreciationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://172.18.17.72/it140p/service.php/unitofProduct", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public float unitofProduct(float cost, float salvagevalue, float usefulLife) {
            object[] results = this.Invoke("unitofProduct", new object[] {
                        cost,
                        salvagevalue,
                        usefulLife});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void unitofProductAsync(float cost, float salvagevalue, float usefulLife) {
            this.unitofProductAsync(cost, salvagevalue, usefulLife, null);
        }
        
        /// <remarks/>
        public void unitofProductAsync(float cost, float salvagevalue, float usefulLife, object userState) {
            if ((this.unitofProductOperationCompleted == null)) {
                this.unitofProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnunitofProductOperationCompleted);
            }
            this.InvokeAsync("unitofProduct", new object[] {
                        cost,
                        salvagevalue,
                        usefulLife}, this.unitofProductOperationCompleted, userState);
        }
        
        private void OnunitofProductOperationCompleted(object arg) {
            if ((this.unitofProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.unitofProductCompleted(this, new unitofProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void calculateInterestCompletedEventHandler(object sender, calculateInterestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calculateInterestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calculateInterestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void calculateInterestRateCompletedEventHandler(object sender, calculateInterestRateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calculateInterestRateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calculateInterestRateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SimpleInterestCompletedEventHandler(object sender, SimpleInterestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SimpleInterestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SimpleInterestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CompoundInterestCompletedEventHandler(object sender, CompoundInterestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompoundInterestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CompoundInterestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void calculateDiscountCompletedEventHandler(object sender, calculateDiscountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calculateDiscountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calculateDiscountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void straightLineDepreciationCompletedEventHandler(object sender, straightLineDepreciationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class straightLineDepreciationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal straightLineDepreciationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void unitofProductCompletedEventHandler(object sender, unitofProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class unitofProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal unitofProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591